# Generated by Django 4.0.3 on 2022-07-17 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['reporter'], 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='reporter',
        ),
    ]
