# Generated by Django 4.0.3 on 2022-07-16 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeReported',
            fields=[
                ('case_file_no', models.CharField(editable=False, max_length=17, primary_key=True, serialize=False, unique=True)),
                ('suspect_name', models.CharField(max_length=100)),
                ('type_of_crime', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_of_crime', models.DateTimeField()),
                ('crime_status', models.CharField(max_length=50)),
                ('crime_reported', models.DateTimeField(auto_now_add=True)),
                ('status_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Crimes Reported',
            },
        ),
        migrations.CreateModel(
            name='OccurenceBook',
            fields=[
                ('id', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('police_station', models.CharField(max_length=100)),
                ('activity', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WantedSuspect',
            fields=[
                ('id', models.CharField(default='65A6DD6FBAA84AF', editable=False, max_length=15, primary_key=True, serialize=False, unique=True)),
                ('suspect_pic', models.ImageField(default='criminal.jpg', upload_to='Suspects-Images/')),
                ('suspect_name', models.CharField(max_length=150)),
                ('alias', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(max_length=7)),
                ('crime', models.CharField(max_length=100)),
                ('bounty', models.PositiveIntegerField(blank=True, default=0)),
                ('last_seen', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('reported', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficialsProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('71b144d9-0ff2-48fb-aaab-23b73a1a4ad1'), editable=False, primary_key=True, serialize=False)),
                ('officer_no', models.CharField(max_length=30)),
                ('police_post', models.CharField(max_length=30)),
                ('rank', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=14)),
                ('dp', models.ImageField(default='officer.png', upload_to='Officer-Dps')),
                ('gender', models.CharField(max_length=7)),
                ('dob', models.DateField(null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('officer', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Officials',
                'ordering': ['officer'],
            },
        ),
    ]
