# Generated by Django 4.0.3 on 2022-07-17 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crimereported',
            name='reported_by',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='officialsprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f5cf61f2-a82c-460c-90ab-bfb604cd0b74'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wantedsuspect',
            name='id',
            field=models.CharField(default='630A8128C82B4D5', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
