# Generated by Django 4.0.3 on 2022-07-17 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0002_crimereported_reported_by_alter_officialsprofile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crimereported',
            name='reported_by',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='officialsprofile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3a70fec3-10f0-46a1-b3ec-e71aca8e1d99'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wantedsuspect',
            name='id',
            field=models.CharField(default='2EE4CFD3ADF1490', editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
