# Generated by Django 4.0.3 on 2022-07-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_alter_crimereported_reported_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialsprofile',
            name='id',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='wantedsuspect',
            name='id',
            field=models.CharField(editable=False, max_length=15, primary_key=True, serialize=False, unique=True),
        ),
    ]
