# Generated by Django 4.0.3 on 2022-07-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0004_alter_officialsprofile_id_alter_wantedsuspect_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialsprofile',
            name='officer_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
