# Generated by Django 4.0.3 on 2022-07-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0005_alter_officialsprofile_officer_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedsuspect',
            name='reported',
            field=models.DateField(auto_now_add=True),
        ),
    ]
