# Generated by Django 4.0.3 on 2022-07-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0006_alter_wantedsuspect_reported'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantedsuspect',
            name='reported',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
